services:
  - type: web
    name: twitch-gemini-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TWITCH_USERNAME
        sync: false
      - key: TWITCH_PASSWORD
        sync: false
      - key: TWITCH_CHANNEL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: UPSTASH_REDIS_URL
        sync: false
